default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: desafio_ninja_development

test:
  <<: *default
  database: desafio_ninja_test

production:
  <<: *default
  database: desafio_ninja_production
  username: desafio_ninja
  password: <%= ENV['DESAFIO_NINJA_DATABASE_PASSWORD'] %>
